//
// ArticlesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire



open class ArticlesAPI {
    /**

     - parameter uuid: (path)  
     - parameter authUser: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter xRealIp: (header)  (optional)
     - parameter textonly: (query)  (optional, default to false)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func articleUuidGet(uuid: UUID, authUser: UUID? = nil, authorization: String? = nil, xRealIp: String? = nil, textonly: Bool? = nil, completion: @escaping ((_ data: Article?,_ error: Error?) -> Void)) {
        articleUuidGetWithRequestBuilder(uuid: uuid, authUser: authUser, authorization: authorization, xRealIp: xRealIp, textonly: textonly).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - GET /article/{uuid}
     - Fetch article by UUID.   Notes about the images:   The image URLs point to our image scaler, and are returned without scaling parameters.  However, if wanted, `width` and `height` parameters can be added to the querystring of the URL.  Also in list views, to ensure same size, it might be useful to crop the images by using the parameter `function=hardcrop`
     - responseHeaders: [Cache-Control(String)]
     - parameter uuid: (path)  
     - parameter authUser: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter xRealIp: (header)  (optional)
     - parameter textonly: (query)  (optional, default to false)
     - returns: RequestBuilder<Article> 
     */
    open class func articleUuidGetWithRequestBuilder(uuid: UUID, authUser: UUID? = nil, authorization: String? = nil, xRealIp: String? = nil, textonly: Bool? = nil) -> RequestBuilder<Article> {
        var path = "/article/{uuid}"
        let uuidPreEscape = "\(APIHelper.mapValueToPathItem(uuid))"
        let uuidPostEscape = uuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{uuid}", with: uuidPostEscape, options: .literal, range: nil)
        let URLString = letteraAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "textonly": textonly
        ])
        let nillableHeaders: [String: Any?] = [
            "AuthUser": authUser,
            "Authorization": authorization,
            "X-Real-Ip": xRealIp
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Article>.Type = letteraAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter uuid: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func articleUuidStubGet(uuid: UUID, completion: @escaping ((_ data: ArticleStub?,_ error: Error?) -> Void)) {
        articleUuidStubGetWithRequestBuilder(uuid: uuid).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - GET /article/{uuid}/stub
     - Fetch an article stub by UUID
     - parameter uuid: (path)  
     - returns: RequestBuilder<ArticleStub> 
     */
    open class func articleUuidStubGetWithRequestBuilder(uuid: UUID) -> RequestBuilder<ArticleStub> {
        var path = "/article/{uuid}/stub"
        let uuidPreEscape = "\(APIHelper.mapValueToPathItem(uuid))"
        let uuidPostEscape = uuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{uuid}", with: uuidPostEscape, options: .literal, range: nil)
        let URLString = letteraAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<ArticleStub>.Type = letteraAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
