//
// CategoriesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire



open class CategoriesAPI {
    /**
     Read categories
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func categoriesGet(completion: @escaping ((_ data: [CategoryHierarchy]?,_ error: Error?) -> Void)) {
        categoriesGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Read categories
     - GET /categories
     - returns: RequestBuilder<[CategoryHierarchy]> 
     */
    open class func categoriesGetWithRequestBuilder() -> RequestBuilder<[CategoryHierarchy]> {
        let path = "/categories"
        let URLString = letteraAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[CategoryHierarchy]>.Type = letteraAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
