//
// Alignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum Alignment: String, Codable {
    case _left = "left"
    case _right = "right"
}
