//
// ArticleType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum ArticleType: String, Codable {
    case nyhetStor = "NyhetStor"
    case nyhetLiten = "NyhetLiten"
    case nyhetRelaterade = "NyhetRelaterade"
    case opinion = "Opinion"
    case katastrofStor = "KatastrofStor"
    case katastrofLiten = "KatastrofLiten"
    case advertorial = "Advertorial"
}
