//
// Article.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Article: Codable {

    public var uuid: UUID
    public var title: String
    public var listTitle: String?
    public var authors: [Author]
    public var tags: [String]
    public var preamble: String?
    public var mainImage: ImageInfo?
    public var listImage: ImageInfo?
    public var body: [Block]
    public var premium: Bool
    public var publishingTime: String
    public var updateTime: String?
    public var articleType: ArticleType
    public var articleTypeDetails: ArticleTypeDetails?
    public var externalScripts: [String]?
    public var relatedArticles: [ArticleStub]
    public var shareUrl: String?
    public var paper: Paper
    public var analyticsCategory: String?
    public var analyticsSection: String?
    public var articlePriority: Int?
    public var articleTimeOnSite: Int?
    public var removeAds: Bool

    public init(uuid: UUID, title: String, listTitle: String?, authors: [Author], tags: [String], preamble: String?, mainImage: ImageInfo?, listImage: ImageInfo?, body: [Block], premium: Bool, publishingTime: String, updateTime: String?, articleType: ArticleType, articleTypeDetails: ArticleTypeDetails?, externalScripts: [String]?, relatedArticles: [ArticleStub], shareUrl: String?, paper: Paper, analyticsCategory: String?, analyticsSection: String?, articlePriority: Int?, articleTimeOnSite: Int?, removeAds: Bool) {
        self.uuid = uuid
        self.title = title
        self.listTitle = listTitle
        self.authors = authors
        self.tags = tags
        self.preamble = preamble
        self.mainImage = mainImage
        self.listImage = listImage
        self.body = body
        self.premium = premium
        self.publishingTime = publishingTime
        self.updateTime = updateTime
        self.articleType = articleType
        self.articleTypeDetails = articleTypeDetails
        self.externalScripts = externalScripts
        self.relatedArticles = relatedArticles
        self.shareUrl = shareUrl
        self.paper = paper
        self.analyticsCategory = analyticsCategory
        self.analyticsSection = analyticsSection
        self.articlePriority = articlePriority
        self.articleTimeOnSite = articleTimeOnSite
        self.removeAds = removeAds
    }


}

