//
// ArticleTypeDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ArticleTypeDetails: Codable {

    public var title: String
    public var description: String?

    public init(title: String, description: String?) {
        self.title = title
        self.description = description
    }


}

