//
// Article.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Article: Codable {

    public var uuid: UUID
    public var title: String
    public var authors: [Author]
    public var tags: [String]
    public var preamble: String?
    public var mainImage: ImageInfo?
    public var listImage: ImageInfo?
    public var body: [Block]
    public var premium: Bool
    public var publishingTime: String
    public var updateTime: String?
    public var articleType: ArticleType
    public var externalScripts: [String]?
    public var relatedArticles: [RelatedArticle]
    public var shareUrl: String?

    public init(uuid: UUID, title: String, authors: [Author], tags: [String], preamble: String?, mainImage: ImageInfo?, listImage: ImageInfo?, body: [Block], premium: Bool, publishingTime: String, updateTime: String?, articleType: ArticleType, externalScripts: [String]?, relatedArticles: [RelatedArticle], shareUrl: String?) {
        self.uuid = uuid
        self.title = title
        self.authors = authors
        self.tags = tags
        self.preamble = preamble
        self.mainImage = mainImage
        self.listImage = listImage
        self.body = body
        self.premium = premium
        self.publishingTime = publishingTime
        self.updateTime = updateTime
        self.articleType = articleType
        self.externalScripts = externalScripts
        self.relatedArticles = relatedArticles
        self.shareUrl = shareUrl
    }


}

