//
// Author.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Author: Codable {

    public var byline: String
    public var image: String?

    public init(byline: String, image: String?) {
        self.byline = byline
        self.image = image
    }


}

