//
// Author.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Author: Codable {

    public var byline: String
    public var image: String?
    public var email: String?

    public init(byline: String, image: String?, email: String?) {
        self.byline = byline
        self.image = image
        self.email = email
    }


}

