//
// Block.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Block: Codable {

    public var paragraph: String?
    public var html: String?
    public var image: ImageInfo?
    public var box: BoxInfo?
    public var headline: String?
    public var footnote: String?
    public var question: String?
    public var quote: String?

    public init(paragraph: String?, html: String?, image: ImageInfo?, box: BoxInfo?, headline: String?, footnote: String?, question: String?, quote: String?) {
        self.paragraph = paragraph
        self.html = html
        self.image = image
        self.box = box
        self.headline = headline
        self.footnote = footnote
        self.question = question
        self.quote = quote
    }


}

