//
// BoxInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct BoxInfo: Codable {

    public var title: String
    public var headline: String?
    public var content: [String]
    public var type: BoxType

    public init(title: String, headline: String?, content: [String], type: BoxType) {
        self.title = title
        self.headline = headline
        self.content = content
        self.type = type
    }


}

