//
// BoxType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum BoxType: String, Codable {
    case fact = "fact"
    case review = "review"
}
