//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum Category: String, Codable {
    case framsidan = "Framsidan"
    case nyheter = "Nyheter"
    case ekonomi = "Ekonomi"
    case nordenOchVarlden = "NordenOchVarlden"
    case finland = "Finland"
    case klimatOchMiljo = "KlimatOchMiljo"
    case kultur = "Kultur"
    case litteratur = "Litteratur"
    case musik = "Musik"
    case scen = "Scen"
    case konst = "Konst"
    case filmOchTv = "FilmOchTv"
    case opinion = "Opinion"
    case ledare = "Ledare"
    case kolumner = "Kolumner"
    case debatt = "Debatt"
    case kronikor = "Kronikor"
    case sport = "Sport"
    case handboll = "Handboll"
    case fotboll = "Fotboll"
    case ishockey = "Ishockey"
    case motorsport = "Motorsport"
    case friidrott = "Friidrott"
    case skidsport = "Skidsport"
    case livsstil = "Livsstil"
    case medicinOchHalsa = "MedicinOchHalsa"
    case familjOchRelationer = "FamiljOchRelationer"
    case matOchDryck = "MatOchDryck"
    case resor = "Resor"
    case bilarOchFordon = "BilarOchFordon"
    case hemOchTradgard = "HemOchTradgard"
}
