//
// CategoryHierarchy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CategoryHierarchy: Codable {

    public var name: String
    public var subcategories: [String]

    public init(name: String, subcategories: [String]) {
        self.name = name
        self.subcategories = subcategories
    }


}

