//
// CategoryHierarchy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CategoryHierarchy: Codable {

    public var name: Category
    public var subcategories: [Category]

    public init(name: Category, subcategories: [Category]) {
        self.name = name
        self.subcategories = subcategories
    }


}

