//
// Cutoff.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Cutoff: Codable {

    public var cutoff: Int
    public var bonus: Int

    public init(cutoff: Int, bonus: Int) {
        self.cutoff = cutoff
        self.bonus = bonus
    }


}

