//
// EventType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum EventType: String, Codable {
    case update = "UPDATE"
    case delete = "DELETE"
    case add = "ADD"
}
