//
// FactInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FactInfo: Codable {

    public var title: String
    public var content: [String]

    public init(title: String, content: [String]) {
        self.title = title
        self.content = content
    }


}

