//
// ImageInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ImageInfo: Codable {

    public var url: String
    public var thumb: String
    public var caption: String?
    public var alignment: Alignment?
    public var byline: String?

    public init(url: String, thumb: String, caption: String?, alignment: Alignment?, byline: String?) {
        self.url = url
        self.thumb = thumb
        self.caption = caption
        self.alignment = alignment
        self.byline = byline
    }


}

