//
// ListArticle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ListArticle: Codable {

    public var uuid: UUID
    public var title: String
    public var authors: [Author]
    public var tags: [String]
    public var preamble: String?
    public var listImage: ImageInfo?
    public var premium: Bool
    public var publishingTime: String
    public var updateTime: String?
    public var relatedArticles: [RelatedArticle]
    public var articleType: ArticleType

    public init(uuid: UUID, title: String, authors: [Author], tags: [String], preamble: String?, listImage: ImageInfo?, premium: Bool, publishingTime: String, updateTime: String?, relatedArticles: [RelatedArticle], articleType: ArticleType) {
        self.uuid = uuid
        self.title = title
        self.authors = authors
        self.tags = tags
        self.preamble = preamble
        self.listImage = listImage
        self.premium = premium
        self.publishingTime = publishingTime
        self.updateTime = updateTime
        self.relatedArticles = relatedArticles
        self.articleType = articleType
    }


}

