//
// Notification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Notification: Codable {

    public var contentType: String
    public var eventid: Int?
    public var eventtype: EventType
    public var uuid: UUID

    public init(contentType: String, eventid: Int?, eventtype: EventType, uuid: UUID) {
        self.contentType = contentType
        self.eventid = eventid
        self.eventtype = eventtype
        self.uuid = uuid
    }


}

