//
// Paper.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum Paper: String, Codable {
    case hbl = "hbl"
    case ht = "ht"
    case vn = "vn"
    case on = "on"
}
