//
// RelatedArticle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RelatedArticle: Codable {

    public var uuid: UUID
    public var title: String
    public var preamble: String?
    public var listImage: ImageInfo?
    public var publishingTime: String
    public var premium: Bool
    public var tags: [String]

    public init(uuid: UUID, title: String, preamble: String?, listImage: ImageInfo?, publishingTime: String, premium: Bool, tags: [String]) {
        self.uuid = uuid
        self.title = title
        self.preamble = preamble
        self.listImage = listImage
        self.publishingTime = publishingTime
        self.premium = premium
        self.tags = tags
    }


}

