//
// Scoring.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Scoring: Codable {

    public var cutoffPriority: [[Any]]
    public var cutoffTimeOnSite: [[Any]]

    public init(cutoffPriority: [[Any]], cutoffTimeOnSite: [[Any]]) {
        self.cutoffPriority = cutoffPriority
        self.cutoffTimeOnSite = cutoffTimeOnSite
    }


}

